// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using todolist.Data;

#nullable disable

namespace todolist.Migrations
{
    [DbContext(typeof(TodoDbContext))]
    [Migration("20251012215637_initial migration")]
    partial class initialmigration
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("todolist.models.Assignment", b =>
                {
                    b.Property<int>("idOfAssignment")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("idOfAssignment"));

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("assignmentDescription")
                        .HasColumnType("text");

                    b.Property<bool>("isDone")
                        .HasColumnType("boolean");

                    b.HasKey("idOfAssignment");

                    b.ToTable("Assignments");
                });
#pragma warning restore 612, 618
        }
    }
}
